### ISSUE TITLE
Medals disappear after a crash

### ISSUE THREAD

**Issue by fragglet** [fragglet/sdl-sopwith#12]
Medals get awarded only after a successful return to base, which makes sense. However, as soon as you crash the plane a single time and lose a life, you lose all the medals you were awarded. It seems rather harsh. A less harsh approach might be that you keep the medals for the duration of the level; this is consistent with the score, which resets to zero at the start of each new level.

@creichen - through some googling I think you were the original implementer of the medals feature, a long long time ago (it finally made it into a release last year when I revived the project!). Do you have any opinions on changing the behavior?

**Comment by creichen** [comment]
Whoah, this is a blast from the past... :-)

I don't have a strong opinions on the matter.  From what little I can remember, the idea was to use the medals as a way to get players to challenge themselves and to engage in risky behaviour while also making it back to the airstrip.  That same incentive would work if they are only awarded after the player lands (not sure if I implemented it that way or not?).

FWIW, the "next level" bit wasn't something I was happy with at the time; from what I remember, my position was that the later levels need more variation before I'd think about how to integrate them, but I never put any appreciable effort into that myself.  It would make sense to carry both the score and the medals over to the next level, in that case.

But yes, making score and medals work consistently makes sense to me, but that would be tricky if you want the score to reset at the start of each level (IIRC there is some award for finishing without losing a plane?).
