### ISSUE TITLE
Add -p argument to set the port number

### ISSUE THREAD

**Issue by aabluedragon** [fragglet/sdl-sopwith#18]
Support for cmd line args such as `-host 23513` (port number) and `-join 88.88.88.88:23513` (host:port).

**Comment by fragglet** [comment]
`-p` would make more sense than `-host` - all existing arguments are single character, and it would match eg. the arguments to netcat.

There's no need to add a new `-join` argument; `-j` can be extended. Actually the manpage says it's already supported?

**Comment by aabluedragon** [comment]
Right, I see it now - https://fragglet.github.io/sdl-sopwith/doc/sopwith.6.html
My bad, somehow I missed this page.
Thanks, you can close the issue I guess.

**Comment by fragglet** [comment]
No, it's still worth keeping the issue so that we can add the ability to change the port servers run on (`-p`)

**Comment by aabluedragon** [comment]
a `-p portnum` argument would be useful.
