### ISSUE TITLE
Add color palette selection to menu and configuration

### ISSUE THREAD

**Issue by techknight** [fragglet/sdl-sopwith#29]
## Summary
When I saw the `#IFDEF LCD` preprocessor directive in `video.c`, I got interested in adding a color palette that similarly replicates my own original experience with Sopwith, except on an amber monochrome CGA monitor.

## Idea
If it's not too big of a change, I'd like to promote that color palette option from preprocessor directive to full configuration option in the menu.

## Example
I roughed together a quick example of what this feature could look like, by adding a new configuration option with a new type:
```c
	{"conf_video_palette",	CONF_INT, {&conf_video_palette}},
```

![sopwith-colors](https://github.com/fragglet/sdl-sopwith/assets/104890/a0c380ba-10ae-4273-8e30-75d00916b07f)
(press the play button to see the colour palette change)

## Questions
1. Would it be more in-line with the spirit of things to simply add my own preprocessor directive instead?
2. If added, is implementing a `CONF_INT` the best way to do it?
3. Since the configuration menu is filling up in terms of numbered options, would a submenu accessed using a letter be preferable? (Similar to how keybindings has its own submenu)

**Comment by fragglet** [comment]
Nice :) I approve. To answer your questions:

1. No #defines, please just add it as a full feature.
2. Yes, CONF_INT is fine.
3. No, let's stick with the one menu for now - there's plenty more screen space for more options for the time being, and we can always use other keys beyond the numbers. Though I do want to be selective about the features we add.

A few thoughts:
* Brainstorming on palettes: we probably also want ones for:
  * [Monochrome](https://www.youtube.com/watch?v=mLVbmnViz7I)
  * [Green screen](https://www.youtube.com/watch?v=Yxf9aBsXOS8)
  * [PC convertible](https://www.youtube.com/watch?v=kAJhmTbOwvw) (LCD, but black foreground)
  * [Tandy 1100FD](https://www.youtube.com/watch?v=SFJ4akFRGVU) (black on green)
  * [Gas Plasma](https://www.youtube.com/watch?v=Qhv0GA_KbV8) - used on some older laptops before LCD technology matured
  * Reversed versions of the LCD versions (the Toshiba laptop I had could have its mono screen reversed via a special keypress)
  * [Alternative CGA palettes](https://www.pixelatedarcade.com/news/alternate-cga-colors-part-2)? Let's not bother with the "low intensity" versions though.
* Let's make sure there's enough contrast to see things properly - the amber scheme in your screenshot makes it look like the two darker shades are hard to distinguish
* Can you locate the palette option on the menu next to the other video options? They're loosely (at least) arranged by function.

Thanks!
