### ISSUE TITLE
Suggestion: Replace macro SOPWITH1_TUNE with a menu option

### ISSUE THREAD

**Issue by NY00123** [fragglet/sdl-sopwith#40]
The idea here is to add a toggle that lets you select between Sopwith 1 and 2's tunes.

Last time I checked it (probably around mid-2023 or a bit later), it was obviously not just a matter of replacing the macro SOPWITH1_TUNE with a variable. I wasn't sure what would be the right approach in case the user changes the tune while it's already playing.

**Comment by fragglet** [comment]
I've considered it in the past but I don't think it would be worth the additional clutter on the options menu. I'm planning to add the ability to override the tune in custom map files so that would be an option for people who really want to hear it instead of the Sopwith 2 tune.

**Comment by NY00123** [comment]
ok, I've actually thought about giving this a try again and implementing it before your comment. Either with the toggle not immediately having an immediate effect while tune is already playing, or the opposite (by stopping tune being played and starting the other one if actual game was not started). I've also thought it should be consistent with the presence of existing menu toggles, like "Solid ground". Given your response, I can leave this by the side.

**Comment by fragglet** [comment]
So if you've already put some work into it, maybe you could adapt your
existing work into adding a new field to the map format? I think it should
be relatively straightforward.

**Comment by NY00123** [comment]
I haven't done such work so far. What I probably did earlier in 2023 was not much more than undefining SOPWITH1_TUNE and inspecting the code.

If you indeed add the feature for user maps, question is if it'll be specific to the maps themselves or also hold to the menu before starting a proper game, say if you add the option of selecting a user map from the menu. But that's probably a topic for discussion outside of this issue, if at all.
