### ISSUE TITLE
Crashing on arrival at Home

### ISSUE THREAD

**Issue by harlankoehn** [fragglet/sdl-sopwith#44]
I've always assumed that some crashing when using the H key and arriving at Home was built into the design. However, It's been a bad enough problem lately that I sometimes will reach game over quite quickly because of it, particularly at higher levels/speeds.

I'm playing Single and Novice and by the time I'm up around 16K points it's difficult to make any successful landing.

**Comment by fragglet** [comment]
The speed increases at the higher levels so yeah, I expect the AI logic that does the landing can't cope. Might be tricky to fix.

**Comment by fragglet** [comment]
Okay, I've made a few slight tweaks that I think improve things quite a bit. [The latest autobuild is here](https://github.com/fragglet/sdl-sopwith/actions/runs/10823449873) if you want to give it a try, or [you can try the web version](https://fragglet.github.io/sdl-sopwith-latest/sopwith.html).

**Comment by fragglet** [comment]
Closing as fixed.
